brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include(("todos.urls"),)),

]

todos/urls.py
# todos/urls.py
from django.urls import path
from .views import todo_list, todo_list_detail, todo_list_create, edit_page, todo_list_delete, todo_item_create, todo_item_update


urlpatterns = [
    path("", todo_list, name="todo_list_list"),
    path("<int:id>/",todo_list_detail, name="todo_list_detail"),
    path("create/", todo_list_create, name="todo_list_create"),
    path("<int:id>/edit/", edit_page, name='todo_list_update'),
    path("<int:id>/delete/", todo_list_delete, name="todo_list_delete"),
    path("items/create/", todo_item_create, name="todo_item_create"),
    path('items/<int:id>/edit/', todo_item_update, name='todo_item_update'),
]

todos/models.py
from django.db import models
from django import forms

# Create your models here.

class TodoList(models.Model):
  name= models.CharField(max_length=100)
  created_on = models.DateTimeField(auto_now_add=True)




class TodoItem (models.Model):
     task = models.CharField(max_length=100)
     due_date = models.DateTimeField( null=True, blank=True,)
     is_completed = models.BooleanField(default=False)
     list = models.ForeignKey(TodoList, related_name="items", on_delete=models.CASCADE)
     objects = models.Manager()

todos/forms.py
from django.forms import ModelForm
from todos.models import TodoList
from .models import TodoItem, TodoList



class TodoListForm(ModelForm):

    class Meta:
        model = TodoList
        fields = [
            "name",
        ]
class EditPageForm(ModelForm):
    class Meta:
        model = TodoList
        fields = [
            'name'
        ]

class TodoItemForm(ModelForm):
    class Meta:
        model = TodoItem
        fields = [
            'task',
            'due_date',
            'is_completed',
            'list',
        ]

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from todos.models import TodoList, TodoItem
from .forms import TodoListForm, EditPageForm, TodoItemForm

def todo_list(request):
    todolist = TodoList.objects.all()
    context = {
        "todo_list": todolist,
    }
    return render(request, "todos/list.html", context)


def todo_list_detail(request, id):
    todolist = get_object_or_404(TodoList, id=id)
    todo_items = TodoItem.objects.filter(list=todolist)
    context = {
        "todo_object": todolist,
        "todo_list_detail": todo_items,
    }
    return render(request, "todos/detail.html", context)


def todo_list_create(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            todo_list = form.save()
            return redirect("todo_list_detail", todo_list.id)
    else:
            form = TodoListForm()

    context = {
            "form" : form,}
    return render(request, "todos/create.html", context)



def edit_page(request, id):
    todolist = get_object_or_404(TodoList, id=id)

    if request.method == "POST":
          form = EditPageForm(request.POST, instance=todolist)
          if form.is_valid():
               form.save()
               return redirect("todo_list_detail", id=todolist.id)
    else:
        form = EditPageForm(instance=todolist)

    context = {
         "form": form,
         "todo_list": todolist
    }
    return render(request, "todos/edit.html", context)


def todo_list_delete(request, id):
    todolist = get_object_or_404(TodoList, id=id)

    if request.method == "POST":
        todolist.delete()
        return redirect("todo_list_list")

    context = {"todo_list": todolist}
    return render(request, "todos/delete.html", context)


def todo_item_create(request):
    todo_lists = TodoList.objects.all()

    if request.method == "POST":
        form = TodoItemForm(request.POST)
        if form.is_valid():
            todo_item = form.save()
            return redirect("todo_list_detail", id=todo_item.list.id)
    else:
        form = TodoItemForm()

    context = {"form": form, "todo_lists": todo_lists}
    return render(request, "todos/item_create.html", context)


def todo_item_update(request, id):
    todo_lists = TodoList.objects.all()

    todo_item = get_object_or_404(TodoItem, id=id)

    if request.method == "POST":
        form = TodoItemForm(request.POST, instance=todo_item)
        if form.is_valid():
            form.save()
            return redirect("todo_list_detail", id=todo_item.list.id)
    else:
        form = TodoItemForm(instance=todo_item)

    context = {"form": form, "todo_item": todo_item, "todo_lists": todo_lists}
    return render(request, "todos/item_update.html", context)

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a New List</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
          </form>
        </div>
    </main>

</body>
</html>

todos/templates/todos/delete.html
<!-- todos/delete.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title> Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                <button>Delete</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Todo Lists</title>
</head>
<body>
  <main>
    <div>
      <h1>{{ todo_object.name }}</h1>
      <header>
        <nav>
          <p>
            <a href="{% url 'todo_list_update' id=todo_object.id %}">Edit</a>
          </p>
            <a href="{% url 'todo_list_delete' id=todo_object.id %}">Delete</a>


        </nav>
      </header>
      <h2>Tasks</h2>
      <table>
        <thead>
          <tr>
            <th>Task</th>
            <th>Due Date</th>
          </tr>
        </thead>
        <tbody>
          {% for todo in todo_object.items.all %}

            <tr>
              <td><a href="{% url 'todo_item_update' id=todo_object.id %}">{{ todo.task }}</a></td>

              <td>{{ todo.due_date }}</td>
            </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
</body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo Lists</title>
</head>
<body>
  <main>
    <div>
    <h1>Update List</h1>
  {% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}
</div>
</main>
</body>
</html>

todos/templates/todos/item_create.html
<!-- todos/item_create.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Todo Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                {% csrf_token %}
                <p>
                    <label for="id_task">Task:</label>
                    <input type="text" name="task" id="id_task" required>
                </p>
                <p>
                    <label for="id_due_date">Due Date:</label>
                    <input type="text" name="due_date" id="id_due_date" required>
                </p>
                <p>
                    <label for="id_is_completed">Is Completed:</label>
                    <input type="checkbox" name="is_completed" id="id_is_completed">
                </p>
                <p>
                    <label for="id_list">List:</label>
                    <select name="list" id="id_list" required>
                        {% for todo_list in todo_lists %}
                            <option value="{{ todo_list.id }}">{{ todo_list.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/item_update.html
<!-- todos/item_update.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Update Todo Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Update item</h1>
            <form method="post">
                {% csrf_token %}
                <p>
                    <label for="id_task">Task:</label>
                    <input type="text" name="task" id="id_task" value="{{ todo_item.task }}" required>
                </p>
                <p>
                    <label for="id_due_date">Due Date:</label>
                    <input type="text" name="due_date" id="id_due_date" value="{{ todo_item.due_date }}" required>
                </p>
                <p>
                    <label for="id_is_completed">Is Completed:</label>
                    <input type="checkbox" name="is_completed" id="id_is_completed" {% if todo_item.is_completed %}checked{% endif %}>
                </p>
                <p>
                    <label for="id_list">List:</label>
                    <select name="list" id="id_list" required>
                        {% for todo_list in todo_lists %}
                            <option value="{{ todo_list.id }}" {% if todo_item.list.id == todo_list.id %}selected{% endif %}>{{ todo_list.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo Lists</title>
</head>

<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <p>
                <a href="{% url 'todo_list_create' %}">Create a new list</a>
            </p>
            <p>
            <a href="{% url 'todo_item_create' %}">Create a new item</a>
            </p>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of Items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo in todo_list %}
                        <tr>
                            <td>
                                <a href="{% url 'todo_list_detail' todo.id %}">{{ todo.name }}</a>
                            </td>
                            <td>{{ todo.items.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>